""" How to play
Rule:
- 1. The lottery is drawn on the first Wednesday of the month.
- 2. The user can buy a ticket a specific number of times. A ticket is a set of 6 numbers
  and the total number between 1 and 55. A ticket can be bought multiple times and
  the ticket price is 10.000 VND one time
- 3. There is also the user can buy a mega 5 number. 
  The mega 5 number is a set of 5 numbers and the total is between 1 and 55 and the 6th number
  will be randomly generated by the remaining.
  The mega 5 number can be bought multiple times and the price is 500.000 VND one time.
  That means when you buy these 5 numbers when 5 numbers win and the 6th number same as the number jackpot,
  you have won the jackpot, but the jackpot is not the same as the 6th number,
  you won the jackpot but only got 40% of the prize.
  winning 4 numbers is 40,000,000 VND, 
  winning 3 numbers is 5,000,000 VND and winning 2 numbers is 500,000 VND, and one number is not. what?
- 4. 6 numbers cannot be the same. The jackpot can be shared by multiple users because
  we can buy multiple tickets by the same number.
  ex: The jackpot is 10 million VND and if the user buys 2 tickets with the same number,
      the jackpot will be shared by the user. The jackpot will be shared 50% by the user and 50% by the other user.
- 5. The user can buy a ticket randomly number or your buffet ticket.
"""
import random


def is_mega655(str_number):
    """ Check number is mega 6/55 or not
    :param number: str
    :return: True if number is mega 655, False if not
    """
    result = False
    if len(str_number) == 12:
        arr_number = list(set(list(map(''.join, zip(*[iter(str_number)] * 2)))))
        if len(arr_number) == 6:
            result = True
    return result


def random_number():
    num = random.randint(1, 55)
    return convert_number_to_str(num)


def random_mega655():
    number_first = random_number()
    number_two = random_number()
    number_three = random_number()
    number_four = random_number()
    number_five = random_number()
    number_six = random_number()
    return number_first + number_two + number_three + number_four + number_five + number_six


def random_ticket():
    ticket = random_mega655()
    while not is_mega655(ticket):
        ticket = random_mega655()
    return ticket


def is_valid(number):
    result = False
    if number in range(1, 56):
        result = True
    return result


def convert_number_to_str(number):
    if number < 10:
        number = "0%s" % str(number)
    return str(number)


def buffet_ticket(number_first, number_two,
                  number_three, number_four,
                  number_five, number_six):
    result = False
    if not is_valid(number_first) or not is_valid(number_two) or not is_valid(number_three) \
            or not is_valid(number_four) or not is_valid(number_five) or not is_valid(number_six):
        return result
    ticket = convert_number_to_str(number_first) + convert_number_to_str(number_two) \
             + convert_number_to_str(number_three) + convert_number_to_str(number_four) \
             + convert_number_to_str(number_five) + convert_number_to_str(number_six)
    if not is_mega655(ticket):
        return result
    return ticket
